basic.forever(function () {
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 50)
    basic.pause(150)
    maqueen.motorStop(maqueen.Motors.M1)
    basic.pause(150)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
    basic.pause(150)
    maqueen.motorStop(maqueen.Motors.M1)
    basic.pause(150)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 60)
    basic.pause(150)
    maqueen.motorStop(maqueen.Motors.M2)
    basic.pause(150)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 60)
    basic.pause(150)
    maqueen.motorStop(maqueen.Motors.M2)
    basic.pause(150)
})
